package com.indraagrotech.commonbeans;

// Generated 21 Nov, 2012 11:40:22 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TblFormMaster generated by hbm2java
 */
public class TblFormMaster implements java.io.Serializable {

	private Integer formId;
	private String formName;
	private String formDesc;
	private Set<TblProductDetails> tblProductDetailses = new HashSet<TblProductDetails>(
			0);

	public TblFormMaster() {
	}

	public TblFormMaster(String formName, String formDesc) {
		this.formName = formName;
		this.formDesc = formDesc;
	}

	public TblFormMaster(String formName, String formDesc,
			Set<TblProductDetails> tblProductDetailses) {
		this.formName = formName;
		this.formDesc = formDesc;
		this.tblProductDetailses = tblProductDetailses;
	}

	public Integer getFormId() {
		return this.formId;
	}

	public void setFormId(Integer formId) {
		this.formId = formId;
	}

	public String getFormName() {
		return this.formName;
	}

	public void setFormName(String formName) {
		this.formName = formName;
	}

	public String getFormDesc() {
		return this.formDesc;
	}

	public void setFormDesc(String formDesc) {
		this.formDesc = formDesc;
	}

	public Set<TblProductDetails> getTblProductDetailses() {
		return this.tblProductDetailses;
	}

	public void setTblProductDetailses(
			Set<TblProductDetails> tblProductDetailses) {
		this.tblProductDetailses = tblProductDetailses;
	}

}
