package com.indraagrotech.commonbeans;

// Generated 21 Nov, 2012 11:40:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * TblLevelMaster generated by hbm2java
 */
public class TblLevelMaster implements java.io.Serializable {

	private Integer levelId;
	private String levelChar;
	private int levelInnumber;
	private int levelIdTag;

	public TblLevelMaster() {
	}

	public TblLevelMaster(String levelChar, int levelInnumber, int levelIdTag) {
		this.levelChar = levelChar;
		this.levelInnumber = levelInnumber;
		this.levelIdTag = levelIdTag;
	}

	public Integer getLevelId() {
		return this.levelId;
	}

	public void setLevelId(Integer levelId) {
		this.levelId = levelId;
	}

	public String getLevelChar() {
		return this.levelChar;
	}

	public void setLevelChar(String levelChar) {
		this.levelChar = levelChar;
	}

	public int getLevelInnumber() {
		return this.levelInnumber;
	}

	public void setLevelInnumber(int levelInnumber) {
		this.levelInnumber = levelInnumber;
	}

	public int getLevelIdTag() {
		return this.levelIdTag;
	}

	public void setLevelIdTag(int levelIdTag) {
		this.levelIdTag = levelIdTag;
	}

}
