package com.indraagrotech.commonbeans;

// Generated 21 Nov, 2012 11:40:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * TblProductDetails generated by hbm2java
 */
public class TblProductDetails implements java.io.Serializable {

	private Integer prodetailsId;
	private TblProductMaster tblProductMaster;
	private TblFormMaster tblFormMaster;
	private String prodetailsPropertyvalue;

	public TblProductDetails() {
	}

	public TblProductDetails(TblProductMaster tblProductMaster,
			TblFormMaster tblFormMaster, String prodetailsPropertyvalue) {
		this.tblProductMaster = tblProductMaster;
		this.tblFormMaster = tblFormMaster;
		this.prodetailsPropertyvalue = prodetailsPropertyvalue;
	}

	public Integer getProdetailsId() {
		return this.prodetailsId;
	}

	public void setProdetailsId(Integer prodetailsId) {
		this.prodetailsId = prodetailsId;
	}

	public TblProductMaster getTblProductMaster() {
		return this.tblProductMaster;
	}

	public void setTblProductMaster(TblProductMaster tblProductMaster) {
		this.tblProductMaster = tblProductMaster;
	}

	public TblFormMaster getTblFormMaster() {
		return this.tblFormMaster;
	}

	public void setTblFormMaster(TblFormMaster tblFormMaster) {
		this.tblFormMaster = tblFormMaster;
	}

	public String getProdetailsPropertyvalue() {
		return this.prodetailsPropertyvalue;
	}

	public void setProdetailsPropertyvalue(String prodetailsPropertyvalue) {
		this.prodetailsPropertyvalue = prodetailsPropertyvalue;
	}

}
