package com.indraagrotech.commonbeans;

// Generated 21 Nov, 2012 11:40:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * TblPowderMaster generated by hbm2java
 */
public class TblPowderMaster implements java.io.Serializable {

	private Integer powId;
	private String powName;
	private String powDesc;

	public TblPowderMaster() {
	}

	public TblPowderMaster(String powName, String powDesc) {
		this.powName = powName;
		this.powDesc = powDesc;
	}

	public Integer getPowId() {
		return this.powId;
	}

	public void setPowId(Integer powId) {
		this.powId = powId;
	}

	public String getPowName() {
		return this.powName;
	}

	public void setPowName(String powName) {
		this.powName = powName;
	}

	public String getPowDesc() {
		return this.powDesc;
	}

	public void setPowDesc(String powDesc) {
		this.powDesc = powDesc;
	}

}
