package com.indraagrotech.commonbeans;

// Generated 21 Nov, 2012 11:40:22 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TblProductMaster generated by hbm2java
 */
public class TblProductMaster implements java.io.Serializable {

	private Integer productId;
	private TblCategoryMaster tblCategoryMaster;
	private String productName;
	private String productDesc;
	private String productApp;
	private String productPacking;
	private int productTag;
	private String productBreadcrumb;
	private String productPrimaryCatId;
	private String productThumbnailUrl;
	private String productLargeimageUrl;
	private String productKeywords;
	private String productCompanyname;
	private String productStockpasteprepare;
	private Set<TblProductDetails> tblProductDetailses = new HashSet<TblProductDetails>(
			0);

	public TblProductMaster() {
	}

	public TblProductMaster(TblCategoryMaster tblCategoryMaster,
			String productName, String productDesc, String productApp,
			String productPacking, int productTag, String productBreadcrumb,
			String productPrimaryCatId, String productThumbnailUrl,
			String productLargeimageUrl, String productKeywords,
			String productCompanyname, String productStockpasteprepare) {
		this.tblCategoryMaster = tblCategoryMaster;
		this.productName = productName;
		this.productDesc = productDesc;
		this.productApp = productApp;
		this.productPacking = productPacking;
		this.productTag = productTag;
		this.productBreadcrumb = productBreadcrumb;
		this.productPrimaryCatId = productPrimaryCatId;
		this.productThumbnailUrl = productThumbnailUrl;
		this.productLargeimageUrl = productLargeimageUrl;
		this.productKeywords = productKeywords;
		this.productCompanyname = productCompanyname;
		this.productStockpasteprepare = productStockpasteprepare;
	}

	public TblProductMaster(TblCategoryMaster tblCategoryMaster,
			String productName, String productDesc, String productApp,
			String productPacking, int productTag, String productBreadcrumb,
			String productPrimaryCatId, String productThumbnailUrl,
			String productLargeimageUrl, String productKeywords,
			String productCompanyname, String productStockpasteprepare,
			Set<TblProductDetails> tblProductDetailses) {
		this.tblCategoryMaster = tblCategoryMaster;
		this.productName = productName;
		this.productDesc = productDesc;
		this.productApp = productApp;
		this.productPacking = productPacking;
		this.productTag = productTag;
		this.productBreadcrumb = productBreadcrumb;
		this.productPrimaryCatId = productPrimaryCatId;
		this.productThumbnailUrl = productThumbnailUrl;
		this.productLargeimageUrl = productLargeimageUrl;
		this.productKeywords = productKeywords;
		this.productCompanyname = productCompanyname;
		this.productStockpasteprepare = productStockpasteprepare;
		this.tblProductDetailses = tblProductDetailses;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public TblCategoryMaster getTblCategoryMaster() {
		return this.tblCategoryMaster;
	}

	public void setTblCategoryMaster(TblCategoryMaster tblCategoryMaster) {
		this.tblCategoryMaster = tblCategoryMaster;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductDesc() {
		return this.productDesc;
	}

	public void setProductDesc(String productDesc) {
		this.productDesc = productDesc;
	}

	public String getProductApp() {
		return this.productApp;
	}

	public void setProductApp(String productApp) {
		this.productApp = productApp;
	}

	public String getProductPacking() {
		return this.productPacking;
	}

	public void setProductPacking(String productPacking) {
		this.productPacking = productPacking;
	}

	public int getProductTag() {
		return this.productTag;
	}

	public void setProductTag(int productTag) {
		this.productTag = productTag;
	}

	public String getProductBreadcrumb() {
		return this.productBreadcrumb;
	}

	public void setProductBreadcrumb(String productBreadcrumb) {
		this.productBreadcrumb = productBreadcrumb;
	}

	public String getProductPrimaryCatId() {
		return this.productPrimaryCatId;
	}

	public void setProductPrimaryCatId(String productPrimaryCatId) {
		this.productPrimaryCatId = productPrimaryCatId;
	}

	public String getProductThumbnailUrl() {
		return this.productThumbnailUrl;
	}

	public void setProductThumbnailUrl(String productThumbnailUrl) {
		this.productThumbnailUrl = productThumbnailUrl;
	}

	public String getProductLargeimageUrl() {
		return this.productLargeimageUrl;
	}

	public void setProductLargeimageUrl(String productLargeimageUrl) {
		this.productLargeimageUrl = productLargeimageUrl;
	}

	public String getProductKeywords() {
		return this.productKeywords;
	}

	public void setProductKeywords(String productKeywords) {
		this.productKeywords = productKeywords;
	}

	public String getProductCompanyname() {
		return this.productCompanyname;
	}

	public void setProductCompanyname(String productCompanyname) {
		this.productCompanyname = productCompanyname;
	}

	public String getProductStockpasteprepare() {
		return this.productStockpasteprepare;
	}

	public void setProductStockpasteprepare(String productStockpasteprepare) {
		this.productStockpasteprepare = productStockpasteprepare;
	}

	public Set<TblProductDetails> getTblProductDetailses() {
		return this.tblProductDetailses;
	}

	public void setTblProductDetailses(
			Set<TblProductDetails> tblProductDetailses) {
		this.tblProductDetailses = tblProductDetailses;
	}

}
